### ISSUE TITLE
[inputs.huawei_telemetry_dialout] Error in plugin: the proto type is nil

### ISSUE THREAD

**Issue by MichaelTharwat** [HuaweiDatacomm/telegraf-huawei-plugin#21]
While trying to run telegraf service to collect telemetry we got below errors in log, operating system is linux debian 10 , systemd is used to run service 

2022-01-24T11:48:53Z E! [inputs.huawei_telemetry_dialout] Error in plugin: the proto type is nil , protoPath is huawei_debug.Debug
2022-01-24T11:48:53Z I! Loaded inputs: huawei_telemetry_dialout
2022-01-24T11:48:53Z I! Loaded aggregators: 
2022-01-24T11:48:53Z I! Loaded processors: 
2022-01-24T11:48:53Z I! Loaded outputs: file
2022-01-24T11:48:53Z I! Tags enabled: host=tele
2022-01-24T11:48:53Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"tele", Flush Interval:30s
2022-01-24T11:49:39Z E! [parsers.huawei_grpc_gpb_parser] E! [grpc parser] get type according protoPath: the proto type is nil , protoPath is huawei_ifm.Ifm
2022-01-24T11:49:39Z E! [inputs.huawei_telemetry_dialout] Error in plugin: the proto type is nil , protoPath is huawei_ifm.Ifm
2022-01-24T11:49:40Z I! Loaded inputs: huawei_telemetry_dialout
2022-01-24T11:49:40Z I! Loaded aggregators: 
2022-01-24T11:49:40Z I! Loaded processors: 
2022-01-24T11:49:40Z I! Loaded outputs: file
2022-01-24T11:49:40Z I! Tags enabled: host=tele
2022-01-24T11:49:40Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"tele", Flush Interval:30s
2022-01-24T11:49:53Z E! [parsers.huawei_grpc_gpb_parser] E! [grpc parser] get type according protoPath: the proto type is nil , protoPath is huawei_debug.Debug

**Comment by caowei49** [comment]
Hi,MichaelTharwat:
You made a mistake in step5 of  Build From Source, you forget to add the mapping of huawei_debug.Debug. You can check HuaweiTelemetry.go(/telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/). you forget to add PathKey{ProtoPath: **"huawei_debug.Debug", Version: "1.0"}: []reflect.Type{reflect.TypeOf((*huawei_debug.Debug)(nil))},** in **var pathTypeMap = map[PathKey][]reflect.Type{}**

**Comment by MichaelTharwat** [comment]
@caowei49 Thank you , Is that mean we need to repeat this step for each sensor path ? like huawei-ifm , huawei-qos, ....etc

**Comment by caowei49** [comment]
yes, you need to repeat this step for each sensor path.

**Comment by MichaelTharwat** [comment]
@caowei49 I am afraid that I am new with go language and protoc , 
I get error  in the perquisites step : protoc-gen-go : go get -u github.com/protobuf/protoc-gen-go@v1.2.0

go get: github.com/protobuf/protoc-gen-go@v1.2.0: invalid version: git ls-remote -q origin in /root/go/pkg/mod/cache/vcs/2a054212b9d0811250f7395e1bba5418745fbe9c52ed18d920706cc173b7b343: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information

**Comment by caowei49** [comment]
HI, you can get protos  : https://github.com/HuaweiDatacomm/proto

**Comment by caowei49** [comment]
go：you can refer to https://go.dev/doc/install
protoc-gen-go: 
vim ~/.bashrc
export GO111MODULE=on
export GOPROXY=https://goproxy.io
export GONOSUMDB=*
source ~/.bashrc
go get -u github.com/golang/protobuf/protoc-gen-go@v1.2.0

**Comment by MichaelTharwat** [comment]
just adding I installed protoc-gen-go v1.25.0-devel 
is there way to use it instead

**Comment by caowei49** [comment]
this is not error, you can find the protoc-gen-go in the goworkplace

**Comment by MichaelTharwat** [comment]
root@michael-pc:/telegraf# make
go mod download -x
go build -ldflags " -X main.commit=77040ef4 -X main.branch=master -X main.goos=linux -X main.goarch=amd64 -X main.version=1.22.0-77040ef4" ./cmd/telegraf
go: updates to go.mod needed; to update it:
	go mod tidy
Makefile:114: recipe for target 'telegraf' failed
make[1]: *** [telegraf] Error 1
Makefile:68: recipe for target 'all' failed
make: *** [all] Error 2
root@michael-pc:/telegraf# go mod tidy
go: finding module for package github.com/influxdata/telegraf/plugins/common/telemetry_proto/huawei_ifm
go: finding module for package github.com/influxdata/telegraf/plugins/common/telemetry_proto
go: finding module for package github.com/harlow/kinesis-consumer/store/ddb
go: finding module for package github.com/harlow/kinesis-consumer
go: found github.com/harlow/kinesis-consumer in github.com/harlow/kinesis-consumer v0.3.5
go: found github.com/harlow/kinesis-consumer/store/ddb in github.com/harlow/kinesis-consumer v0.3.5
go: finding module for package github.com/influxdata/telegraf/plugins/common/telemetry_proto
go: finding module for package github.com/influxdata/telegraf/plugins/common/telemetry_proto/huawei_ifm
github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb tested by
	github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb.test imports
	github.com/influxdata/telegraf/plugins/common/telemetry_proto: no matching versions for query "latest"
github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb tested by
	github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb.test imports
	github.com/influxdata/telegraf/plugins/common/telemetry_proto/huawei_ifm: no matching versions for query "latest"

**Comment by caowei49** [comment]
you can use telegraf this version:
https://github.com/influxdata/telegraf/tree/release-1.20
and try again

**Comment by MichaelTharwat** [comment]
Ok thank you , please confirm below syntax also for huawei-ifm and huawei-qos
var pathTypeMap = map[PathKey][]reflect.Type{
PathKey{ProtoPath: "huawei_debug.Debug", Version: "1.0"}: []reflect.Type{reflect.TypeOf((*huawei_debug.Debug)(nil))},
PathKey{ProtoPath: "huawei_ifm.Ifm", Version: "1.0"}: []reflect.Type{reflect.TypeOf((*huawei_ifm.Ifm)(nil))},
PathKey{ProtoPath: "huawei_qos.Qos", Version: "1.0"}: []reflect.Type{reflect.TypeOf((*huawei_qos.Qos)(nil))},
}

**Comment by caowei49** [comment]
yes,that is ok.don't forget add some codes at line 3,like this
import (
	"fmt"
	"github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/huawei_debug"
	"github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/huawei_ifm"
        "github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/huawei_qos"
	"google.golang.org/protobuf/proto"
	"reflect"
)

**Comment by MichaelTharwat** [comment]
go build -ldflags " -X main.commit=34ad5aa1 -X main.branch=release-1.20 -X main.goos=linux -X main.goarch=amd64 -X main.version=1.20.4" ./cmd/telegraf


# github.com/influxdata/telegraf/plugins/parsers
plugins/parsers/registry.go:9:1: selfstat redeclared in this block
	plugins/parsers/registry.go:5:1: other declaration of selfstat
plugins/parsers/registry.go:9:1: imported and not used: "github.com/influxdata/telegraf/selfstat"
plugins/parsers/registry.go:10:1: models redeclared in this block
	plugins/parsers/registry.go:6:1: other declaration of models
plugins/parsers/registry.go:10:1: imported and not used: "github.com/influxdata/telegraf/models"
plugins/parsers/registry.go:11:1: huawei_grpc_gpb redeclared in this block
	plugins/parsers/registry.go:7:1: other declaration of huawei_grpc_gpb
plugins/parsers/registry.go:11:1: imported and not used: "github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_gpb"
plugins/parsers/registry.go:12:1: huawei_grpc_json redeclared in this block
	plugins/parsers/registry.go:8:1: other declaration of huawei_grpc_json
plugins/parsers/registry.go:12:1: imported and not used: "github.com/influxdata/telegraf/plugins/parsers/huawei_grpc_json"
plugins/parsers/registry.go:457:6: NewHuaweiGrpcGpbParser redeclared in this block
	plugins/parsers/registry.go:432:6: other declaration of NewHuaweiGrpcGpbParser
plugins/parsers/registry.go:471:6: NewHuaweiGrpcJsonParser redeclared in this block
	plugins/parsers/registry.go:446:6: other declaration of NewHuaweiGrpcJsonParser
plugins/parsers/registry.go:12:1: too many errors

**Comment by caowei49** [comment]
you maybe run the install.sh two times.the install.sh only run once.

**Comment by MichaelTharwat** [comment]
telegraf binary file is generated now , thank you and I will close this issue and open new for metrics issues .
