### ISSUE TITLE
dial_out Plugin decoding problem

### ISSUE THREAD

**Issue by MichaelTharwat** [HuaweiDatacomm/telegraf-huawei-plugin#23]
Issue : Service is running without errors and tcpdump shows that data is sent by router , however telegraf doesn't write metrics to influxdb , we used same output plugin configuration is used with cisco mdt and it is working on same influxdb, below router and telegraf configuration also attached tcpdump result . 
[result.pcap.txt](https://github.com/HuaweiDatacomm/telegraf-huawei-plugin/files/8429580/result.pcap.txt)

#Telegraf Configuration

###############################################################################
#                                                                      GLOBAL CONFIG                                                                     #
###############################################################################

[agent]

  interval = "60s"
  flush_interval = "30s"
  logfile = "/tmp/telegraf_hua.log"

###############################################################################
#                                                                    SERVICE INPUT PLUGINS                                                          #
###############################################################################

[[inputs.huawei_telemetry_dialout]]
service_address = ":10001"
data_format = "grpc"
transport = "grpc"

###############################################################################
#                                                                           OUTPUT PLUGINS                                                              #
###############################################################################

[[outputs.influxdb]]
   database = "timor"
   urls = ["http://localhost:8086"]
   retention_policy = "autogen"
***********************************************************************************************************************************
#Huawei NE40 Router Configuration 
<Obour_NE40_TB>display current-configuration configuration telemetry
#
telemetry
#
sensor-group sensor1
  sensor-path huawei-debug:debug/cpu-infos/cpu-info
  sensor-path huawei-debug:debug/memory-infos/memory-info
  sensor-path huawei-ifm:ifm/interfaces/interface
#
destination-group desgroup1
  ipv4-address 10.53.225.254 port 10001 vpn-instance OAM protocol grpc no-tls
#
subscription subscription1
  local-source-address ipv4 10.154.244.145
  sensor-group sensor1
  destination-group desgroup1

**Comment by caowei49** [comment]
you can view  telegraf_hua.log . There may be other mistakes.

**Comment by MichaelTharwat** [comment]
no errors in log file (), may you share telegraf.bin file that you use if it is possible  
[telegraf_hua.log](https://github.com/HuaweiDatacomm/telegraf-huawei-plugin/files/8441347/telegraf_hua.log)

**Comment by caowei49** [comment]
I view the log, no errors in log file, but no data. the service_address = ":10001" in input ,Do you forget to write the ip or omit the ip

**Comment by MichaelTharwat** [comment]
there was no errors in log because I made mistake in service to reload on failure but I removed it and service worked for 1 min only then generate below failure , please advise 

telegraf-hua.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf-hua.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-04-07 14:24:18 EET; 2min 34s ago
     Docs: https://github.com/influxdata/telegraf
  Process: 24098 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf_hua.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=exited, status
 Main PID: 24098 (code=exited, status=2)

Apr 07 14:24:18 timor telegraf[24098]: google.golang.org/grpc.(*Server).processStreamingRPC(0xc001376e00, {0x5e337d0, 0xc001690000}, 0xc000e257a0, 0xc000d6d7d0, 0x
Apr 07 14:24:18 timor telegraf[24098]:         /usr/local/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1532 +0xece
Apr 07 14:24:18 timor telegraf[24098]: google.golang.org/grpc.(*Server).handleStream(0xc001376e00, {0x5e337d0, 0xc001690000}, 0xc000e257a0, 0x0)
Apr 07 14:24:18 timor telegraf[24098]:         /usr/local/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1612 +0x9d6
Apr 07 14:24:18 timor telegraf[24098]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Apr 07 14:24:18 timor telegraf[24098]:         /usr/local/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x98
Apr 07 14:24:18 timor telegraf[24098]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Apr 07 14:24:18 timor telegraf[24098]:         /usr/local/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x28a
Apr 07 14:24:18 timor systemd[1]: telegraf-hua.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 07 14:24:18 timor systemd[1]: telegraf-hua.service: Failed with result 'exit-code'.

**Comment by caowei49** [comment]
you also can  try dialin to test telegraf write metrics to influxdb

**Comment by MichaelTharwat** [comment]
@caowei49 may you please support with link to download your telegraf.bin file that you use .

**Comment by caowei49** [comment]
the link of protoc-gen-go ?

**Comment by MichaelTharwat** [comment]
No , I mean "telegraf" the binary file that is generated (compiled) at your environment , if it possible to upload it to something like google drive then I will download it and try to test in my environment , thanks .

**Comment by MichaelTharwat** [comment]
Hi @caowei49 , we tried to run dial_out again and got below error , please advise 

"panic: interface conversion: *huawei_debug.Debug is not protoreflect.ProtoMessage: missing method ProtoReflect"

**Comment by caowei49** [comment]
Are you add huawei_debug protoreflect in HuaweiTelemetry ? Please check step 6 and 7.

**Comment by MichaelTharwat** [comment]
yes , I added it . when I searched for this error I found below link states that issue may be due to different protoc-gen-go versions , for example I found that huawei-telemetry.pb.go is generated with version 1.26.0 and protoc 3.17 while I generated huawei-debug.pb.go with 1.2.0 and protoc 3.14 as mentioned in steps .

https://stackoverflow.com/questions/65563409/importing-proto-files-from-different-package-causes-missing-method-protoreflect

**Comment by caowei49** [comment]
hello,you can delete the protoc-gen-go@v1.2.0, then **go get -u github.com/golang/protobuf/protoc-gen-go**.
put proto file in this dir(telegraf/plugins/parsers/huawei_grpc_gpb), add **option go_package="/huawei_debug";** in proto file(under the "package" option). then regenerate huawei-debug.pb.go.

**Comment by MichaelTharwat** [comment]
> hello,you can delete the protoc-gen-go@v1.2.0, then **go get -u github.com/golang/protobuf/protoc-gen-go**. put proto file in this dir(telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto), add **option go_package="/huawei_debug";** in proto file(under the "package" option). then regenerate huawei-debug.pb.go.

Hi , do you mean create dir huawei_debug first then put huawei-debug.proto in dir (telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/huawei_debug) then follow modification steps ?

**Comment by MichaelTharwat** [comment]
> > hello,you can delete the protoc-gen-go@v1.2.0, then **go get -u github.com/golang/protobuf/protoc-gen-go**. put proto file in this dir(telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto), add **option go_package="/huawei_debug";** in proto file(under the "package" option). then regenerate huawei-debug.pb.go.
> 
> Hi , do you mean create dir huawei_debug first then put huawei-debug.proto in dir (telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto/huawei_debug) then follow modification steps ?

just adding I tried both , to create dir huawei_debug and try to generate pb file and I don't created dir huawei_debug and followed above steps but this error appeared "huawei-debug.proto:11:1: Expected top-level statement (e.g. "message")."

**Comment by MichaelTharwat** [comment]
> 

thanks Anthony I will try it :)

**Comment by caowei49** [comment]
**option package="/huawei_debug";**    you forget to add the **option** 
you can delete the dir huawei_debug,  add option package="/huawei_debug" in proto,  generate the proto can generate folders and go file ,you can put proto in this dir (telegraf/plugins/parsers/huawei_grpc_gpb/telemetry_proto) ，then step 8, you can try it.

**Comment by MichaelTharwat** [comment]
> 

@caowei49 It is working now , thank you so much , we will validate metrics collected , thanks again !
